CREATE DATABASE M_InLock

USE M_InLock

CREATE TABLE Usuarios(
	UsuarioId INT IDENTITY PRIMARY KEY,
	Email VARCHAR(255) NOT NULL UNIQUE,
	Senha VARCHAR(255) NOT NULL,
	PermissaoUsuario VARCHAR(255) NOT NULL
);

CREATE TABLE Estudios(
	EstudioId  INT IDENTITY PRIMARY KEY,
	NomeEstudio VARCHAR(255) NOT NULL UNIQUE,
	PaisOrigem VARCHAR(255) NOT NULL,
	DataCriacao DATE NOT NULL,
	UsuarioId INT NOT NULL FOREIGN KEY REFERENCES Usuarios(UsuarioId)
);

CREATE TABLE Jogos(
	JogoId INT IDENTITY PRIMARY KEY,
	NomeJogo VARCHAR(255) NOT NULL,
	Descricao TEXT NOT NULL,
	DataLancamento DATE NOT NULL,
	Valor FLOAT NOT NULL,
	EstudioId INT NOT NULL FOREIGN KEY REFERENCES Estudios(EstudioId)

);

